// vdr-export.js - Export VDR to DOCX format
// Dynamically loads docx.js library

// Store the loaded library
let docxLib = null;

/**
 * Load the docx library dynamically
 */
async function loadDocxLibrary() {
  if (docxLib) {
    return docxLib;
  }

  // Check if already loaded globally
  if (typeof window.docx !== 'undefined') {
    docxLib = window.docx;
    return docxLib;
  }

  // Try to load via dynamic import from CDN
  try {
    console.log('[VDR Export] Loading docx library from CDN...');
    
    // Use the ESM version from skypack or esm.sh which provides proper ES module exports
    const module = await import('https://esm.sh/docx@8.5.0');
    docxLib = module;
    console.log('[VDR Export] Library loaded successfully via ESM import');
    return docxLib;
  } catch (err) {
    console.error('[VDR Export] Failed to load via ESM:', err);
  }

  // Fallback: try unpkg
  try {
    const module = await import('https://unpkg.com/docx@8.5.0/build/index.es.js');
    docxLib = module;
    console.log('[VDR Export] Library loaded successfully via unpkg');
    return docxLib;
  } catch (err) {
    console.error('[VDR Export] Failed to load via unpkg:', err);
  }

  throw new Error('Could not load DOCX library. Please check your internet connection.');
}

/**
 * Generate and download DOCX file
 */
export async function generateDocx(vdr) {
  // Load the docx library
  const lib = await loadDocxLibrary();
  
  if (!lib) {
    throw new Error('DOCX library not loaded.');
  }

  console.log('[VDR Export] docx library ready, generating document...');

  const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType,
    LevelFormat
  } = lib;

  // Format dates
  const baselineDate = formatDateForDoc(vdr.baselineDate);
  const generatedDate = formatDateForDoc(vdr.generatedDate);
  
  // Build document filename
  const safeVentureName = vdr.ventureName.replace(/[^\w\s-]/g, '').replace(/\s+/g, '_');
  const filename = `VDR - ${safeVentureName} - ${generatedDate}.docx`;

  // Build document content
  const content = [];

  // Title
  content.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [
        new TextRun({
          text: `VDR - ${vdr.ventureName} - ${generatedDate}`,
          bold: true
        })
      ]
    })
  );

  // Metadata section
  const metaParts = [];
  if (vdr.portfolio) {
    metaParts.push(`Portfolio: ${vdr.portfolio}`);
  }
  metaParts.push(`Baseline Date: ${baselineDate}`);
  if (vdr.advisorName) {
    metaParts.push(`Advisor: ${vdr.advisorName}`);
  }
  if (vdr.isHealthRelated) {
    metaParts.push(`Health-Related Venture`);
  }

  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: metaParts.join(' | '),
          size: 20, // 10pt
          italics: true
        })
      ],
      spacing: { after: 120 }
    })
  );

  // Summary
  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `${vdr.categoriesWithGaps} categories with advancement goals • ${vdr.totalGap} total levels to advance`,
          size: 22 // 11pt
        })
      ],
      spacing: { after: 400 }
    })
  );

  // Add horizontal line
  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "─".repeat(80),
          size: 16,
          color: "CCCCCC"
        })
      ],
      spacing: { after: 200 }
    })
  );

  // Sections
  for (const section of vdr.sections) {
    // Category heading
    content.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [
          new TextRun({
            text: `${section.category} (Current: ${section.baselineLevel} → Goal: ${section.goalLevel})`,
            bold: true
          })
        ],
        spacing: { before: 300, after: 120 }
      })
    );

    // Deliverables as bullet list
    for (const deliverable of section.deliverables) {
      content.push(
        new Paragraph({
          numbering: {
            reference: "vdr-bullets",
            level: 0
          },
          children: [
            new TextRun({
              text: deliverable,
              size: 24 // 12pt
            })
          ],
          spacing: { after: 80 }
        })
      );
    }

    // Add spacing after section
    content.push(
      new Paragraph({
        children: [],
        spacing: { after: 200 }
      })
    );
  }

  // Footer
  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "─".repeat(80),
          size: 16,
          color: "CCCCCC"
        })
      ],
      spacing: { before: 400, after: 120 }
    })
  );

  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by NobleReach RL Goals & VDR Companion Tool",
          size: 18, // 9pt
          italics: true,
          color: "666666"
        })
      ]
    })
  );

  // Create document
  const doc = new Document({
    styles: {
      default: {
        document: {
          run: {
            font: "Arial",
            size: 24 // 12pt
          }
        }
      },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: {
            size: 32, // 16pt
            bold: true,
            font: "Arial"
          },
          paragraph: {
            spacing: { before: 240, after: 240 },
            outlineLevel: 0
          }
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: {
            size: 28, // 14pt
            bold: true,
            font: "Arial"
          },
          paragraph: {
            spacing: { before: 200, after: 120 },
            outlineLevel: 1
          }
        }
      ]
    },
    numbering: {
      config: [
        {
          reference: "vdr-bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "•",
              alignment: AlignmentType.LEFT,
              style: {
                paragraph: {
                  indent: { left: 720, hanging: 360 }
                }
              }
            }
          ]
        }
      ]
    },
    sections: [
      {
        properties: {
          page: {
            size: {
              width: 12240, // 8.5 inches in DXA
              height: 15840 // 11 inches in DXA
            },
            margin: {
              top: 1440, // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440
            }
          }
        },
        children: content
      }
    ]
  });

  // Generate and download
  console.log('[VDR Export] Packing document...');
  const buffer = await Packer.toBlob(doc);
  console.log('[VDR Export] Downloading file:', filename);
  downloadBlob(buffer, filename);
}

/**
 * Format date for document display
 */
function formatDateForDoc(dateStr) {
  if (!dateStr) return 'Unknown';
  try {
    const date = new Date(dateStr);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  } catch {
    return dateStr.split('T')[0];
  }
}

/**
 * Download blob as file
 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
